name: ethiopian_calendar
description: A Flutter application to demonstrate Abushakir dart package.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_bloc: ^3.2.0
  meta: ^1.1.6
  equatable: ^1.0.0
  abushakir: ^0.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true